### PR TITLE
Modified band filter for G11

### PR DESCRIPTION
**Pull request by florintanasa**
G11 multiband have 7 bands like G59, 
also I try to use for first time for me how can I work in a team with git.

### CODE REVIEW

**Comment by wd8rde** [comment]
Very good Florin. Thank you.
I have been in bed since Sunday with very painful back problem.

**Comment by florintanasa** [comment]
Oh, I think now you are more better.

**Comment by florintanasa** [comment]
Bob,
I not have write access for libExtio_genesis so if you accept you can done this modification ?

**Comment by wd8rde** [comment]
I merged your pull request. Thanks Florin.

**Comment by florintanasa** [comment]
Also I thank you.

**Pull request merged**
